services:
  
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-infra-monitor
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "InfraMonitor@123"
    ports:
      - "1433:1433"

  api:
    build:
      context: ./backend/InfraMonitorAPI
      dockerfile: Dockerfile
    image: infra-monitor-api:latest
    container_name: infra-api
    ports:
      - "5000:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=database,1433;Database=InfraMonitorDB;User Id=sa;Password=InfraMonitor@123;TrustServerCertificate=True;"
    depends_on:
      - database

  agent:
    build:
      context: ./backend/monitor-agent
      dockerfile: Dockerfile
    image: infra-monitor-agent:latest
    container_name: infra-agent
    environment:
      API_URL: http://api:8080/api
    depends_on:
      - api

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: infra-monitor-frontend:latest
    container_name: infra-frontend
    ports:
      - "3000:80"
    depends_on:
      - api
